---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  template:
    spec:
      containers:
        - name: redis
          image: redis:alpine
          volumeMounts:
            - name: redis
              mountPath: /data
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
---
kind: Service
apiVersion: v1
metadata:
  name: redis
spec:
  ports:
    - port: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
