apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patchesStrategicMerge:
  - patch-custom-domain.yml
  - patch-no-ha.yml
  - patch-zerossl.yml
  - patch-delete-ns-cert.yml
