---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-redis-from-super
spec:
  podSelector:
    matchLabels:
      component: redis
  ingress:
    - from:
        - podSelector:
            matchLabels:
              component: super
      ports:
        - port: 6379
          protocol: TCP
