---
apiVersion: v1
kind: Namespace
metadata:
  name: stream-simy-me
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stream 
  annotations:
    custom-hostname: stream
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "2"
        autoscaling.knative.dev/targetUtilizationPercentage: "80"
    spec:
      containerConcurrency: 50
      containers:
        - image: adamyordan/laplace
          ports:
            - containerPort: 3000
              name: http1
          command:
          - /root/laplace
          - --addr=127.0.0.1:3000
          - --tls=false
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 256Mi
