apiVersion: v1
kind: Namespace
metadata:
  name: super
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super
spec:
  template:
    spec:
      containers:
        - name: super
          image: quay.io/sim/super
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: super
          volumeMounts:
            - name: super-data
              mountPath: /data
        - name: gluetun
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          image: qmcgaw/gluetun
          envFrom:
            - configMapRef:
                name: gluetun-config
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-net-tun
              readOnly: true
      volumes:
        - name: super-data
          persistentVolumeClaim:
            claimName: super
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: super
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
